# Agent Configuration
MAX_RECIPES_TO_RETURN = 3
MAX_SEARCH_QUERIES = 3
MAX_RETRY_ATTEMPTS = 1

# Scoring Weights
LEARNING_VALUE_WEIGHT = 30
SKILL_MATCH_WEIGHT = 25
RECENCY_WEIGHT = 20
SOURCE_QUALITY_WEIGHT = 15
DIVERSITY_WEIGHT = 10

# Tavily Configuration
TAVILY_MAX_RESULTS = 3
TAVILY_SEARCH_DEPTH = "advanced"
TAVILY_INCLUDE_DOMAINS = ["seriouseats.com"]

# LLM Configuration
DEFAULT_MODEL = "gpt-3.5-turbo"
DEFAULT_TEMPERATURE = 0.7
MAX_TOKENS = 1000
